<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-FF5U5J9" name="tests.LoginTests" tests="4" failures="1" timestamp="29 Nov 2018 14:51:15 GMT" time="54.874" errors="0">
  <testcase name="invalidLoginTest_InvalidUserNameInvalidPassword" time="12.513" classname="tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [or favor, entre com um usuário e senha corretos. Note que ambos os campos diferenciam maiúsculas e minúsculas.] but found [Por favor, entre com um usuário e senha corretos. Note que ambos os campos diferenciam maiúsculas e minúsculas.]">
      <![CDATA[java.lang.AssertionError: expected [or favor, entre com um usuário e senha corretos. Note que ambos os campos diferenciam maiúsculas e minúsculas.] but found [Por favor, entre com um usuário e senha corretos. Note que ambos os campos diferenciam maiúsculas e minúsculas.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.LoginPage.verifyLoginPassword(LoginPage.java:39)
at tests.LoginTests.invalidLoginTest_InvalidUserNameInvalidPassword(LoginTests.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalidLoginTest_InvalidUserNameInvalidPassword -->
  <testcase name="invalidLoginTest_InvalidUserNameInvalidPassword" time="14.160" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- invalidLoginTest_InvalidUserNameInvalidPassword -->
  <testcase name="validLoginTest_ValidUserNameValidPassword" time="16.670" classname="tests.LoginTests"/>
  <testcase name="verifyLink" time="11.531" classname="tests.LoginTests"/>
</testsuite> <!-- tests.LoginTests -->
